class Constants:
    '''
    GEN_SETS = "GenSets"
    GEN_VARIABLES = "GenVariables"
    GEN_PARAMETERS = "GenParameters"
    '''
    SYMBOLIC = "symbolic"
    LOGICAL = "logical"
    BINARY_0_1 = "{0,1}"
    BINARY = "binary"
    INTEGER = "integer"
    REALSET = "realset"
    
    PARAMETERS = "parameters"
    VARIABLES = "variables"
    SETS = "sets"


INT = "int"
BOOL = "bool"
FLOAT = "float"
STRING = "string"
SET_OF_INT = "set of int"
INDEX_SET_ = "INDEX_SET_"
ARRAY = "array"
ENUM = "enum"
TO_ENUM = "to_enum"
OF = "of"
IN = "in"
BY = "by"
VAR = "var"
SET = "set"
ASSIGN = "="
EQUAL = "="
NEQ = "!="
LE = "<="
LT = "<"
GE = ">="
GT = ">"
INCLUDE = "include"
IF = "if"
THEN = "then"
ELSEIF = "elseif"
ELSE = "else"
ENDIF = "endif"
SUCH_THAT = "|"
WHERE = "where"
FROM_TO = ".."
AND = "/\\"
OR = "\\/"
BACKSPACE = "\\"
ANDLITERAL = "and"
ORLITERAL = "or"
NOT = "not"
TRUE = "true"
FALSE = "false"
SOLVE = "solve"
SATISFY = "satisfy"
CONSTRAINT = "constraint"
FORALL = "forall"
SUM = "sum"
POW = "pow"
FLOOR = "floor"
LN = "ln"
TRUNC = "trunc"
DIV = "/"
MOD = "mod"
MINUS = "-"

BEGIN_SET = "{"
END_SET = "}"
BEGIN_ARGUMENT_LIST = "("
END_ARGUMENT_LIST = ")"
BEGIN_ARRAY = "["
END_ARRAY = "]"
COMMA = ","
SPACE = " "
EMPTY_STRING = ""
SEP_PARTS_DECLARATION = ":"
END_STATEMENT = ";"
BREAKLINE = "\n"
TAB = "\t"
UNDERLINE = "_"
PERIOD = "."

INDEX = "index"
INDEX1 = "index1"
INDEX2 = "index2"
INDICES = "indices"
SET = "set"
ZERO = "0"
TYPE = "type"
ISSETWITHINDICES = "isSetWithIndices"
NEW_INDICES = "new_indices"
REALTYPE = "realtype"
DIMEN = "dimen"
INDEXOF = "indexOf"
POS = "pos"
IDENTIFIERS = "identifiers"
IDENTIFIER = "identifier"
ORDER = "order"
SETWITHINDICES = "setWithIndices"
CONTEXT = "context"
NEWENTRYLOGICALEXPRESSION = "newEntryLogicalExpression"

DOMAIN = "domain"
DOMAINS = "domains"
DOMAINS_WITH_INDICES_LIST = "domains_with_indices_list"
DEPENDENCIES = "dependencies"
SUB_INDICES = "sub_indices"
TYPES = "types"
DIM = "dim"
MINVAL = "minVal"
MAXVAL = "maxVal"

STATEMENT = "statement"
SCOPE = "scope"
SCOPES = "scopes"
TABLE = "table"
TABLES = "tables"
LEVEL = "level"
LASTSCOPE = "lastScope"
ISDECLARATION = "isDeclaration"

REGEX_IDENTIFIER = "^[_a-zA-Z][_a-zA-Z0-9]*$"
REGEX_ARGUMENT_LIST = "\([_a-zA-Z][_a-zA-Z0-9]*(,[_a-zA-Z][_a-zA-Z0-9]*)\)*\s+"
REGEX_INDICES_SET_OPERATION = "\[([a-zA-Z0-9][a-zA-Z0-9,]*)\]"
REGEX_BETWEEN_QUOTES = '"(?:[^\\\\]|\\\\.)*?(?:"|$)|\'(?:[^\\\\]|\\\\.)*?(?:\'|$)'

ASSERT = "assert"
QUOTE = "\""
ASSERTION = "Assertion"
FAILED = "failed!"

LET="let"
PREDICATE="predicate"
TEST="test"
FUNCTION="function"
ANNOT="::"